### ISSUE TITLE
StatusBarInfo conflict with Edit Image

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder-docs-samples#3]
1. Open Edit Image.
2. Result: status bar is show at the bottom (wrong).
3. Close Edit Image.
4. Result: status bar is now transparent (wrong).

Ad 2)

![screen shot 2015-08-26 at 14 16 45](https://cloud.githubusercontent.com/assets/545175/9493029/f9d71e54-4bfc-11e5-9e2d-5fe6c2e5c574.png)

Ad 4)

![screen shot 2015-08-26 at 14 16 58](https://cloud.githubusercontent.com/assets/545175/9493032/fde5f312-4bfc-11e5-9c5a-443121ec054a.png)

**Comment by jodator** [comment]
Closed by fixes in CKFinder repo.
