### ISSUE TITLE
CustomButton plugin is a bit confusing

### ISSUE THREAD

**Issue by wwalc** [ckfinder/ckfinder-docs-samples#6]
The `toolbar:reset:Main` event is fired only when toolbar for resource type is fired. As a result the "Send Feedback" button does not appear if anything else but resource type is focused. 

On the other side, the feedback item in the context menu is displayed for files and folder. 

For consistency, the toolbar button should appear in the same scenario (when file/folder/resource type is focused).

![screen shot 2015-10-02 at 13 56 48](https://cloud.githubusercontent.com/assets/545175/10246011/9fa62474-690d-11e5-9a7e-294255bb7ea7.png)

**Comment by jodator** [comment]
Nope.

>  Generic toolbar event fired before changing toolbar configuration

So this is an event to hook on when a user want to add a button to Main toolbar regardless its config.

Anyway no bug here.

**Comment by jodator** [comment]
But there is a bug on CKFinder toolbar
